Zorang\Bundle\AkeneoRulesComposer\Entity\Rule:
    properties:
        code:
            - Type:
                type: string
            - NotBlank: ~
            - Regex:
               pattern: /^[a-zA-Z0-9_]+$/
               message: Rule code may contain only letters, numbers and underscores
            - Length:
               max: 255
        priority:
            - Type:
                type: int
            - Regex:
                pattern: /^[0-9]+$/
                message: Priority  may contain only numbers





